### ISSUE TITLE
Add option to get items from everywhere, not just stockpiles

### ISSUE THREAD

**Issue by thomotron** [PhinixTeam/Phinix#25]
### Description
Add an option to the mod menu to scan the whole map for items, rather than just pulling from stockpiles. This should fix compatibility issues with various other storage mediums, though it might feel a bit cheaty since items need not be stockpiled to be traded.

See the [original suggestion on Discord](https://discordapp.com/channels/363547745564360704/475843225656229916/605072274340708374).

**Comment by lilwhitemouse** [comment]
I have added #40 which is a slightly different issue (and represents items in storage not being accessible, as opposed to random items on the map).
