### ISSUE TITLE
Buildings_Storage are not counted as stockpiles by Phinix

### ISSUE THREAD

**Issue by lilwhitemouse** [PhinixTeam/Phinix#40]
### Description
Describe why you're opening the issue:  users of Deep Storage complain that items in storage are not available for trade.

### Steps to reproduce
1. Install SolydX
2. ...
3. Profit!!

### Further detail
In TradeWindow.cs's PreOpen(), itemStacks are initialized to a collection of items from all the stockpiles in all the maps.  However, vanilla Shelves (and all storage mods' buildings, as far as I know) are of the type Building_Storage.  For an item to be "stored," all the game cares is that it is collected in a ISlotGroupParent's SlotGroup.  This includes both stockpile zones and storage buildings.

You probably want to use map.haulDestinationManager.AllGroups as a way to get a full list of SlotGroups (perhaps using HeldThings to get your items?)

(As far as I know, all storage mods use buildings that are both ISlotGroupParents as well as IHaulDestination, so the haulDestinationManager should be fine. If anyone ever makes a storage mod that has slotGroups that are not? They'll probably need to keep AllGroups up to date anyway to keep rimworld functional.)

Happy trading!

**Comment by thomotron** [comment]
Cheers for pointing out `map.haulDestinationManager`, I've just given it a quick test and it works flawlessly in place of the old stockpile logic.

**Comment by thomotron** [comment]
I've given it a test with a variety of storage mods, including Deep Storage, and had no issues so this'll be out in the next release
