### ISSUE TITLE
[Feature request] Clear previous selection when adding to trade

### ISSUE THREAD

**Issue by exuvo** [PhinixTeam/Phinix#49]
## Description
After adding stuff to the trade, clear previous selection (the bottom part of trade UI)
Example:
I set wood to 1 and press add so it jump up.
Then we discuss in trade chat and other party wants something else, so i search for gold and set it to 1 and press add again.
But now trade has 2 wood and 1 gold as wood was still selected.

I at least would prefer if it did not remember previous selection.

**Comment by thomotron** [comment]
Yeah that's pretty gross and shouldn't be happening.

**Comment by exuvo** [comment]
Wonderful!
