### ISSUE TITLE
text wrapping

### ISSUE THREAD

**Issue by Lazy-Spiff** [PhinixTeam/Phinix#7]
### Description
it borked

### Steps to reproduce
write long walls of text

**Comment by thomotron** [comment]
ok

**Comment by thomotron** [comment]
On a more serious note, this seems to be an issue with how RimWorld handles text wrapping on buttons. Labels are always wrapped fine, buttons are not.

**Comment by thomotron** [comment]
Clickable chat messages will be disabled in the next release and replaced with ordinary text. You can still trade with people by clicking their names in the user list on the right-hand side of the chat pane.
